Traceback (most recent call last):
  File "ForwardRun_test.py", line 196, in <module>
    trace = GetTrace(PREFIX,0,optimal=False)
  File "../Utilities/newfun_full.py", line 299, in GetTrace
    chain_idx = len(outlist[0])-12; chunck_idx = len(outlist[0])-9
IndexError: list index out of range
/var/spool/slurmd/job498001/slurm_script: line 19: /home/users/yanlan: Is a directory
