Traceback (most recent call last):
  File "ForwardRun_smassim.py", line 307, in <module>
    res = nanOLS(np.column_stack([TS[0][i,::2],dLAI[::2]]), TS[0][i,1::2])
  File "../Utilities/Utilities.py", line 143, in nanOLS
    mod = sm.OLS(y[nanfilter], X[nanfilter])
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py", line 817, in __init__
    hasconst=hasconst, **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py", line 663, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py", line 179, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py", line 212, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py", line 64, in __init__
    **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py", line 87, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/data.py", line 633, in handle_data
    **kwargs)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/data.py", line 79, in __init__
    self._handle_constant(hasconst)
  File "/home/users/yanlan/anaconda3/lib/python3.6/site-packages/statsmodels/base/data.py", line 131, in _handle_constant
    ptp_ = self.exog.ptp(axis=0)
ValueError: zero-size array to reduction operation maximum which has no identity
/var/spool/slurmd/job3134216/slurm_script: line 19: /home/users/yanlan: Is a directory
